### ISSUE TITLE
Issue with baseURL in API docs for different projects

### ISSUE THREAD

**Issue by TheTamT3** [Particle-Network/particle-docs-mintlify#115]
I am currently using Mintlify as a centralized management platform for the API docs of my projects. During implementation, I encountered an issue with the baseURL for some of the API docs.

Specifically, I have two projects with identical endpoints, for example: "GET /api/manage/health_check", but different baseURLs. However, when displayed in the UI, the baseURL for Project B is shown as the same as Project A, whereas they should be different.

I would greatly appreciate your assistance in resolving this issue.

Thank you for your support, and I look forward to hearing from you soon.

**Comment by TABASCOatw** [comment]
Hi, please reach out to the Mintlify team, we're not affiliated.
